name: tv_indoor
description: "Tv-Indoor"
publish_to: 'none' 

version: 1.1.0+5

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  http: ^1.1.0
  video_player: ^2.9.3
  webview_flutter: ^4.11.0
  mobile_device_identifier: ^0.0.3
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  flutter_cache_manager: ^3.4.1
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.1.0
  weather_icons: ^3.0.0
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/img-sidebar/image-side.png
    - assets/logos/logo-sidebar.png
    - assets/logos/logoTV01.png
    - assets/logos/Logo Rayquimica-1.png





