name: tv_indoor
description: "Tv-Indoor"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  video_player: ^2.9.3
  webview_flutter: ^4.11.0
  mobile_device_identifier: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/midias/videoplayback.mp4
    - assets/midias/img1.jpeg
    - assets/midias/img2.jpeg


